### PR TITLE
Multiple issues #67 fixes

### LINKED ISSUE #68: Remove buy back and burns from roadmap (Q2 to Q4)
Screen Shot 2022-06-30 at 11 16 31 AM

### PR DESCRIPTION
**Pull request by Buko-pie**
for https://github.com/mgguild/mgguild.github.io/issues/67
closes https://github.com/mgguild/mgguild.github.io/issues/68

- tab title changes
- home page changes
- teams changes
- partners text edit
- removed buy back programs in roadmap Q2-Q4

_(noice)_

### CODE REVIEW

**Review by swengr-janan — CHANGES_REQUESTED** [review]
@Buko-pie pa change ini to **_White Paper | MetaGaming Guild (MGG)_**
Screen Shot 2022-06-30 at 12 03 39 PM
*

**Comment by swengr-janan** [comment]
Ini din @Buko-pie , Koji Adriano dapat
Screen Shot 2022-06-30 at 12 09 32 PM

Add mo na din si Emman Adornado (QA Specialist) and John Anthony Balbin (Lead QA Specialist)

Also pa remove na si John Carlo Ariola sa list

**Review by EAdornado — APPROVED** [review]
All goods!

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
