### PR TITLE
NFT page updates

### LINKED ISSUE #79: MGG Website polishes
Replace Countdown for minting button on NFT Page.
image

Discription Polishes.
image
image

### PR DESCRIPTION
**Pull request by Buko-pie**
closes https://github.com/mgguild/mgguild.github.io/issues/79

- added NFT gif in NFT page
- countdown timer and text changes
- added configs

### CODE REVIEW

**Review by EAdornado — APPROVED** [review]
All Goods!

**Review by kojiadrianojr — APPROVED** [review]
LGTM!

**Review by swengr-janan — CHANGES_REQUESTED** [review]
Dapat PFP NFTs, bako lang PFP
Screen Shot 2022-07-19 at 3 07 45 PM
Screen Shot 2022-07-19 at 3 07 21 PM

**Review by EAdornado — APPROVED** [review]
All goods!

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
