### PR TITLE
Add new team members

### LINKED ISSUE #112: Update team member's avatar
Here is the link: https://drive.google.com/drive/folders/1GsXtrVWVGd4s9qzWYK7djBENWLDFNMox?usp=sharing

### PR DESCRIPTION
**Pull request by kojiadrianojr**
Update teams and assets
closes #112

### CODE REVIEW

**Review by swengr-janan — CHANGES_REQUESTED** [review]
Change the following

Mike Reveno -> Mike Reñevo
Trainerer -> Trainer

Reference:
Screen Shot 2022-09-08 at 9 38 22 PM
Screen Shot 2022-09-08 at 9 37 41 PM

**Review by EAdornado — CHANGES_REQUESTED** [review]
Position title has extra 'm' on community

image

**Comment by kojiadrianojr** [comment]
Updated @mgguild/quality-assurance

**Review by EAdornado — APPROVED** [review]
LGTM

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
